version: 0.2

# Environment variables
env:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"

# Build phases
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - echo "Setting up JAVA_HOME..."
      - export JAVA_HOME=$JAVA21_HOME
      - echo "JAVA_HOME is set to $JAVA_HOME"
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version
      - echo "Installation phase completed"

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - pwd
      - echo "Listing project files:"
      - ls -la
      - echo "Checking pom.xml:"
      - head -20 pom.xml
      - echo "Pre-build phase completed"

  build:
    commands:
      - echo "Build phase started..."
      - echo "Running tests..."
      - mvn test
      - echo "Building JAR file..."
      - mvn clean package -DskipTests
      - echo "Verifying JAR file..."
      - ls -la target/
      - test -f "target/slack.cab-0.0.1-SNAPSHOT.jar" && echo "JAR file found" || (echo "JAR file not found!" && exit 1)
      - ls -lh target/slack.cab-0.0.1-SNAPSHOT.jar
      - du -h target/slack.cab-0.0.1-SNAPSHOT.jar
      - echo "Build phase completed successfully"

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Final verification:"
      - ls -la target/
      - echo "Build completed successfully!"
      - echo "Artifact ready at target/slack.cab-0.0.1-SNAPSHOT.jar"

# Artifacts to be uploaded to S3
artifacts:
  files:
    - target/slack.cab-0.0.1-SNAPSHOT.jar
  name: slack-cab-build
  base-directory: '.'

# Cache Maven dependencies for faster builds
cache:
  paths:
    - '/root/.m2/**/*'

# Reports (optional - for test results)
reports:
  surefire-reports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    file-format: 'JUNITXML'
